#!/usr/bin/env bash
set -euo pipefail
# regenerate-manifest.sh — Recovery utility for worktrees created without new-session.sh (mec. M)
# SSoT model: docs/process/parallel-sessions-protocol.md § D8 + D13
#
# Usage:
#   scripts/git/regenerate-manifest.sh                  # interactive
#   scripts/git/regenerate-manifest.sh --auto           # best-effort from path + branch (no prompts)
#
# Reads:
#   - cwd (git rev-parse --show-toplevel) → infer brand + slug + worktree_type
#   - git branch --show-current → confirm branch
#   - origin/main HEAD SHA
#
# Asks (interactive) or infers (--auto):
#   - story_id (from slug + manifest absent)
#   - tickets (comma-sep list, optional)
#   - created_by_skill (default: chris-manual)
#   - notes
#
# Writes:
#   - .session.yaml en cwd
# Idempotent: si ya existe manifest, prompt overwrite (interactive) o skip (--auto).

AUTO=false
[[ "${1:-}" = "--auto" ]] && AUTO=true

CWD="$(git rev-parse --show-toplevel)"
BASENAME="$(basename "${CWD}")"
BRANCH="$(git branch --show-current)"

# Infer brand + slug + type. Brand enum from the seam (project.config.yaml · harness_config.py)
# — no hardcoded list (charter §3 DIP · W5b 2026-06-09). Loud-degrade to empty if unreadable.
KNOWN_BRANDS="$("${CWD}/.venv/bin/python" "${CWD}/scripts/harness_config.py" brands.loop_order 2>/dev/null | tr '\n' ' ')"
[ -z "${KNOWN_BRANDS}" ] && echo "::warning::project.config.yaml brands.loop_order unreadable — brand inference degraded" >&2

if [[ "${BASENAME}" = "luana-platform" ]]; then
  echo "::error::PRINCIPAL worktree no requiere manifest. Aborting."
  exit 1
elif [[ "${BASENAME}" =~ ^luana-core-(.+)$ ]]; then
  BRAND="core"
  WORKTREE_TYPE="ephemeral"
  SLUG="${BASH_REMATCH[1]}"
elif [[ "${BASENAME}" =~ ^luana-([a-z]+)$ ]]; then
  B="${BASH_REMATCH[1]}"
  if echo " ${KNOWN_BRANDS} " | grep -q " ${B} "; then
    BRAND="${B}"
    WORKTREE_TYPE="canonical"
    SLUG=""
  else
    echo "::error::Unknown brand in path '${BASENAME}'. Allowed brands: ${KNOWN_BRANDS}"
    exit 1
  fi
elif [[ "${BASENAME}" =~ ^luana-([a-z]+)-(.+)$ ]]; then
  B="${BASH_REMATCH[1]}"
  S="${BASH_REMATCH[2]}"
  if echo " ${KNOWN_BRANDS} " | grep -q " ${B} "; then
    BRAND="${B}"
    WORKTREE_TYPE="ephemeral"
    SLUG="${S}"
  else
    echo "::error::Unknown brand in path '${BASENAME}'. Allowed brands: ${KNOWN_BRANDS}"
    exit 1
  fi
else
  echo "::error::Cannot infer brand/type from path '${BASENAME}'"
  exit 1
fi

MANIFEST="${CWD}/.session.yaml"

# Idempotency
if [[ -f "${MANIFEST}" ]]; then
  if $AUTO; then
    echo "→ Manifest already exists, skipping (--auto)"
    exit 0
  fi
  read -p "Manifest exists. Overwrite? [y/N] " confirm
  [[ "${confirm}" != "y" && "${confirm}" != "Y" ]] && { echo "Aborted."; exit 0; }
fi

# Story ID
STORY_ID="${SLUG}"
if ! $AUTO && [[ -z "${STORY_ID}" ]]; then
  read -p "Story ID: " STORY_ID
fi

# Lane (only ephemeral may have one — but optional)
LANE=""
if ! $AUTO && [[ "${WORKTREE_TYPE}" = "ephemeral" ]]; then
  read -p "Lane (optional, e.g. be|fe|tests|docs): " LANE
fi

# Tickets
TICKETS_ARR="[]"
if ! $AUTO; then
  read -p "Tickets (comma-sep, optional, e.g. T-2,T-3): " tix_raw
  if [[ -n "${tix_raw}" ]]; then
    TICKETS_ARR="[$(echo "${tix_raw}" | sed 's/,/, /g')]"
  fi
fi

# Skill / notes
CREATED_BY="chris-manual"
if ! $AUTO; then
  read -p "Created by skill [chris-manual]: " input_skill
  [[ -n "${input_skill}" ]] && CREATED_BY="${input_skill}"
fi
NOTES=""
if ! $AUTO; then
  read -p "Notes (optional): " NOTES
fi

# Origin main SHA (best-effort)
git fetch origin main --quiet 2>/dev/null || true
ORIGIN_SHA="$(git rev-parse origin/main 2>/dev/null || echo 'unknown')"

# Write manifest
cat > "${MANIFEST}" <<EOF
# Manifest regenerated by regenerate-manifest.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
# SSoT: docs/process/parallel-sessions-protocol.md § D8 + D13
# Este archivo NO se versiona (debe estar gitignored).
brand: ${BRAND}
worktree_type: ${WORKTREE_TYPE}
story_id: ${STORY_ID}
lane: ${LANE}
tickets: ${TICKETS_ARR}
created_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
created_by_skill: ${CREATED_BY}
parent_branch: origin/main
parent_sha: ${ORIGIN_SHA}
branch: ${BRANCH}
notes: "${NOTES}"
last_sync:
  fetched_at: null
  origin_main_sha: ${ORIGIN_SHA}
  result: nothing
  commits_pulled: 0
  core_touched: false
EOF

echo "✓ Manifest written: ${MANIFEST}"
echo "  brand: ${BRAND}"
echo "  worktree_type: ${WORKTREE_TYPE}"
echo "  story_id: ${STORY_ID:-—}"
echo "  branch: ${BRANCH}"
