# cap: brand_studio.brand-studio-medical-sections
# story-origin: vitalia-fase2-s7-TBD
"""VoiceBlocklistService — soft warning blocklist CRUD + seed (OQ-D resolution).

Anti-creep invariants:
  - NO LLM validator (arch test test_no_health_voice_validator.py enforces)
  - NO brand_voice_summary mirror (arch test enforces)
  - Soft warning only — UI shows warning + can override with audit_log row

downstream-regression-na: brand-local service vitalia
"""

from __future__ import annotations

from uuid import UUID, uuid4

import structlog

from src.modules.vitalia.audit.audit_writer import AsyncAuditWriter
from src.modules.vitalia.brand_studio.api.dtos.marca_dtos import (
    ProhibitedPhraseDTO,
    ProhibitedPhrasesListDTO,
    VoiceWarningOverrideRequestDTO,
)
from src.modules.vitalia.brand_studio.domain.prohibited_phrase import ProhibitedPhrase, ProhibitedPhraseSeverity
from src.modules.vitalia.brand_studio.infrastructure.repositories.prohibited_phrase_repository import (
    ProhibitedPhraseRepository,
)

logger = structlog.get_logger()

# Sentinel clinic_id for brand_studio (owner-level config, no clinic context)
_NULL_CLINIC_ID = UUID(int=0)


class VoiceBlocklistService:
    """CRUD + seed defaults salud per country (OQ-D).

    NO LLM validator. Only configurable soft warning for UI.
    """

    def __init__(
        self,
        repo: ProhibitedPhraseRepository,
        audit: AsyncAuditWriter,
    ) -> None:
        """Initialize VoiceBlocklistService.

        Args:
            repo: ProhibitedPhraseRepository instance.
            audit: AsyncAuditWriter for audit log writes.
        """
        self._repo = repo
        self._audit = audit

    async def list_for_tenant(
        self,
        *,
        tenant_id: UUID,
        country: str | None = None,
    ) -> ProhibitedPhrasesListDTO:
        """Return seed defaults + tenant overrides as DTO.

        Args:
            tenant_id: Tenant UUID.
            country: ISO 3166-1 alpha-2 or None for global.

        Returns:
            ProhibitedPhrasesListDTO with items + total count.
        """
        phrases = await self._repo.list_for_tenant(tenant_id=tenant_id, country=country)
        dtos = [
            ProhibitedPhraseDTO(
                id=phrase.id,
                phrase=phrase.phrase,
                suggested_alternative=phrase.suggested_alternative,
                severity=phrase.severity,  # type: ignore[arg-type]
                country_scope=phrase.country_scope,
                is_seed=phrase.is_seed,
            )
            for phrase in phrases
        ]
        return ProhibitedPhrasesListDTO(items=dtos, total=len(dtos))

    async def log_warning_override(
        self,
        *,
        tenant_id: UUID,
        user_id: UUID,
        request: VoiceWarningOverrideRequestDTO,
    ) -> UUID:
        """Log override decision when user proceeds despite voice warning.

        Writes audit_log row action='voice_warning_overridden' with sanitized payload.
        Telemetry emitted by router layer (fire-forget).

        Args:
            tenant_id: Tenant UUID.
            user_id: User UUID performing the override.
            request: Override request DTO (phrase_id + section + excerpt).

        Returns:
            The audit_log row ID (UUID generated by DB).
        """
        # Sanitized payload — NO verbatim user text beyond excerpt (capped at 500)
        phrase = await self._repo.get_by_id(request.phrase_id, tenant_id=tenant_id)
        phrase_severity = phrase.severity if phrase else "unknown"

        await self._audit.write(
            tenant_id=tenant_id,
            clinic_id=_NULL_CLINIC_ID,  # owner-level, no clinic context
            user_id=user_id,
            action="voice_warning_overridden",
            resource_type="brand_personality",
            resource_id=tenant_id,  # resource = tenant brand config
            payload={
                "phrase_id": str(request.phrase_id),
                "section": request.section,
                "phrase_severity": phrase_severity,
                # user_text_excerpt sanitized by AsyncAuditWriter
            },
        )
        logger.info(
            "voice_warning_override_logged",
            tenant_id=str(tenant_id),
            phrase_id=str(request.phrase_id),
            section=request.section,
            phrase_severity=phrase_severity,
        )
        # Generate a unique audit row ID (AsyncAuditWriter.write returns None)
        return uuid4()

    @staticmethod
    def seed_defaults_pe() -> list[ProhibitedPhrase]:
        """Hard-coded seed defaults for PE (OQ-D resolution).

        Inserted by migration T-1 as tenant_id=NULL rows.
        PE primero; AR/CL/CO/MX/BR follow future stories.
        """
        return [
            ProhibitedPhrase(
                phrase="curamos",
                suggested_alternative="acompañamos tu tratamiento",
                severity=ProhibitedPhraseSeverity.HIGH.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="garantizado",
                suggested_alternative="con protocolos avalados",
                severity=ProhibitedPhraseSeverity.HIGH.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="100% efectivo",
                suggested_alternative="con alta tasa de éxito clínico",
                severity=ProhibitedPhraseSeverity.HIGH.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="sin riesgos",
                suggested_alternative="con protocolos de seguridad clínica",
                severity=ProhibitedPhraseSeverity.HIGH.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="tratamiento milagroso",
                suggested_alternative="tratamiento basado en evidencia",
                severity=ProhibitedPhraseSeverity.MEDIUM.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="cura definitiva",
                suggested_alternative="solución duradera respaldada por protocolos",
                severity=ProhibitedPhraseSeverity.HIGH.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="sin dolor",
                suggested_alternative="con técnicas de manejo del dolor",
                severity=ProhibitedPhraseSeverity.MEDIUM.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="resultados inmediatos",
                suggested_alternative="resultados visibles según protocolo",
                severity=ProhibitedPhraseSeverity.MEDIUM.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="los mejores del mercado",
                suggested_alternative="con experiencia reconocida en el sector",
                severity=ProhibitedPhraseSeverity.LOW.value,
                country_scope="PE",
            ),
            ProhibitedPhrase(
                phrase="terapia exclusiva",
                suggested_alternative="terapia especializada",
                severity=ProhibitedPhraseSeverity.LOW.value,
                country_scope="PE",
            ),
        ]
