# cap: clinics.lisa.doctores
"""BioPublic domain entity — 3 editable sections for doctor public bio.

Pure Python dataclass — zero framework imports (DDD domain layer).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BioPublic:
    """Public bio of a doctor: 3 content-editable sections.

    Authored by admin_clinic via autosave or generated by BioGenerationService.
    Stored as JSONB in vitalia_doctors.bio_public.
    """

    resumen: str | None = None
    """Resumen profesional: breve presentación del médico."""

    formacion: str | None = None
    """Formación académica y especialidades."""

    enfoque: str | None = None
    """Enfoque clínico o especialización principal."""

    def is_empty(self) -> bool:
        """True when all sections are None or empty."""
        return not any([self.resumen, self.formacion, self.enfoque])

    def to_dict(self) -> dict[str, str | None]:
        """Serialize to dict for JSONB storage."""
        return {
            "resumen": self.resumen,
            "formacion": self.formacion,
            "enfoque": self.enfoque,
        }

    @classmethod
    def from_dict(cls, data: dict[str, str | None] | None) -> "BioPublic | None":
        """Deserialize from JSONB dict (returns None if data is None)."""
        if data is None:
            return None
        return cls(
            resumen=data.get("resumen"),
            formacion=data.get("formacion"),
            enfoque=data.get("enfoque"),
        )
