// cap: scheduling.mateo-agenda
// story-origin: vitalia-fase2-s1-TBD
/**
 * payments.ts — Payment mutation hook for Valeria Agenda.
 * T-12 vitalia-fase2-valeria-agenda
 *
 * useChargeMutation: POST /api/v1/payments/charge
 * - Caller MUST generate idempotencyKey (UUID v4) before calling mutate()
 * - X-Idempotency-Key prevents double-charges on network retry
 * - Invalidates grid + appointment detail on success
 *
 * downstream-regression-na: brand-local FE hook; no cross-brand consumers
 * spec_anchor: 03-arch.md § 5.1 + 06-tickets.yaml T-12
 */

"use client";

import { useAuth } from "@clerk/nextjs";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { vitaliaFetch } from "@/lib/fetch-client";
import { useClinicId } from "@/hooks/useClinicId";
import { useActorHeaders } from "@/hooks/useActorHeaders";
import type { ChargeResponseDTO } from "../types/agenda-schema";
import { agendaKeys } from "./agenda";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ChargeMutationVariables {
  appointmentId: string;
  /** ISO 4217 currency code for this transaction */
  currency: string;
  /** Amount to charge in cents */
  amountCents: number;
  /** Payment method */
  method: "cash" | "card" | "transfer" | "mercadopago" | "other";
  /** UUID v4 — MUST be generated by caller (crypto.randomUUID()) */
  idempotencyKey: string;
  /** Optional: fiscal document type to emit immediately */
  emitFiscalDoc?: "factura" | "boleta" | "ticket" | null;
}

// ── useChargeMutation ─────────────────────────────────────────────────────────

/**
 * Mutation hook for charging a patient appointment balance.
 *
 * Usage:
 *   const { mutate, isPending } = useChargeMutation(tenantId);
 *   const idempotencyKey = crypto.randomUUID();
 *   mutate({ appointmentId, currency, amountCents, method, idempotencyKey });
 */
export function useChargeMutation(tenantId: string) {
  const { getToken } = useAuth();
  const clinicId = useClinicId();
  const actorHeaders = useActorHeaders();
  const queryClient = useQueryClient();

  return useMutation<ChargeResponseDTO, Error, ChargeMutationVariables>({
    mutationFn: async ({
      appointmentId,
      currency,
      amountCents,
      method,
      idempotencyKey,
      emitFiscalDoc,
    }) => {
      const token = await getToken();
      if (!token) throw new Error("Not authenticated");

      const payload = {
        appointment_id: appointmentId,
        currency,
        amount_cents: amountCents,
        method,
        emit_fiscal_doc: emitFiscalDoc ?? null,
      };

      // payments/charge requires the HIPAA-lite dual filter + audit actor
      // (X-Clinic-ID + X-User-ID + X-User-Role) alongside the idempotency key.
      return vitaliaFetch<ChargeResponseDTO>("/api/v1/payments/charge", {
        method: "POST",
        token,
        tenantId,
        headers: {
          ...actorHeaders,
          ...(clinicId ? { "X-Clinic-ID": clinicId } : {}),
          "X-Idempotency-Key": idempotencyKey,
        },
        body: JSON.stringify(payload),
      });
    },
    onSuccess: (_, { appointmentId }) => {
      // Invalidate grid (paymentStatus badge updates) + drawer detail
      void queryClient.invalidateQueries({ queryKey: agendaKeys.all(tenantId) });
      void queryClient.invalidateQueries({
        queryKey: agendaKeys.detail(tenantId, appointmentId),
      });
    },
  });
}
