# cap: marketing.attribution-matrix-4-origins
# story-origin: TBD
"""Pydantic v2 DTOs for the vitalia marketing module.

Covers:
  - BowtieSummaryResponse — bowtie funnel KPI snapshot
  - StageDetailResponse — per-stage channel breakdown
  - ChannelDetailResponse — single channel metrics
  - LucasRecommendationResponse — recommendation card
  - ApproveRecommendationRequest / RejectRecommendationRequest — mutation inputs
  - AttributionMatrixResponse — attribution matrix snapshot
  - ReferralsResponse — referrals leaderboard snapshot
  - OAuthConnectRequest / OAuthConnectResponse — OAuth flow initiation
  - SyncResponse — connection sync status

PII rules (pii-sanitisation.md):
  - All responses have explicit model_config + fields (no wildcard PHI leak).
  - top_referrers use referrer_id (UUID hash), no patient names.

Currency: currency fields typed str | None (NEVER defaulted "USD").
          Callers set from tenant locale or provider data.

downstream-regression-na: brand-local marketing application DTOs
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from src.modules.vitalia.marketing.domain.enums import (
    BowtieStage,
    ProviderSlug,
    RejectReason,
)

# ---------------------------------------------------------------------------
# Channel / Bowtie DTOs
# ---------------------------------------------------------------------------


class ChannelDetailResponse(BaseModel):
    """Performance metrics for a single ad channel on a given day."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    tenant_id: UUID
    clinic_id: UUID
    provider: str
    channel_slug: str
    campaign_id: str | None
    campaign_name: str | None
    metric_date: date
    impressions: int
    clicks: int
    conversions: int
    spend_cents: int
    currency: str | None = None


class StageDetailResponse(BaseModel):
    """Per-stage channel breakdown for the bowtie funnel.

    channels: list of ChannelDetailResponse for this stage's date range.
    """

    model_config = ConfigDict(from_attributes=True)

    stage: BowtieStage
    channels: list[ChannelDetailResponse]
    total_impressions: int
    total_clicks: int
    total_conversions: int
    total_spend_cents: int
    currency: str | None = None


class BowtieSummaryResponse(BaseModel):
    """Bowtie funnel KPI snapshot per clinic for a date range.

    One entry per stage (attract / convert / retain) with aggregated metrics.
    """

    model_config = ConfigDict(from_attributes=True)

    tenant_id: UUID
    clinic_id: UUID
    period_start: date
    period_end: date
    stages: list[StageDetailResponse]
    currency: str | None = None


# ---------------------------------------------------------------------------
# Lucas Recommendations DTOs
# ---------------------------------------------------------------------------


class LucasRecommendationResponse(BaseModel):
    """Single marketing recommendation generated by Lucas AI."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    tenant_id: UUID
    clinic_id: UUID
    stage: str
    recommendation_kind: str
    title: str
    body: str
    rationale_json: dict[str, Any]
    priority: int
    status: str
    expires_at: datetime
    action_payload_json: dict[str, Any] | None = None
    confidence_pct: int | None = None
    projected_impact_text: str | None = None
    approved_by_user_id: UUID | None = None
    approved_at: datetime | None = None
    undo_until: datetime | None = None
    rejected_by_user_id: UUID | None = None
    rejected_at: datetime | None = None
    reject_reason: str | None = None
    created_at: datetime
    updated_at: datetime


class ApproveRecommendationRequest(BaseModel):
    """Request body for approving a Lucas recommendation."""

    model_config = ConfigDict(from_attributes=True)

    user_id: UUID


class RejectRecommendationRequest(BaseModel):
    """Request body for rejecting a Lucas recommendation."""

    model_config = ConfigDict(from_attributes=True)

    user_id: UUID
    reason: RejectReason


# ---------------------------------------------------------------------------
# Attribution DTOs
# ---------------------------------------------------------------------------


class AttributionMatrixResponse(BaseModel):
    """Attribution matrix snapshot — revenue by channel for a period."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    tenant_id: UUID
    clinic_id: UUID
    period_start: date
    period_end: date
    channel_breakdown: dict[str, Any]
    total_attributed_revenue: Decimal
    currency: str | None = None
    computed_at: datetime


# ---------------------------------------------------------------------------
# Referrals DTOs
# ---------------------------------------------------------------------------


class ReferrerEntryResponse(BaseModel):
    """Single referrer entry in the leaderboard.

    HIPAA: referrer_id is a UUID hash — NO patient names stored.
    """

    model_config = ConfigDict(from_attributes=True)

    referrer_id: str
    referral_count: int
    converted_count: int
    rank: int


class ReferralsResponse(BaseModel):
    """Referrals leaderboard snapshot for a clinic period."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    tenant_id: UUID
    clinic_id: UUID
    period_start: date
    period_end: date
    top_referrers: list[ReferrerEntryResponse]
    total_referrals: int
    total_converted: int
    computed_at: datetime


# ---------------------------------------------------------------------------
# OAuth / Sync DTOs
# ---------------------------------------------------------------------------


class OAuthConnectRequest(BaseModel):
    """Request to initiate OAuth flow for an ad channel provider."""

    model_config = ConfigDict(from_attributes=True)

    provider: ProviderSlug
    redirect_uri: str


class OAuthConnectResponse(BaseModel):
    """Response with OAuth authorization URL for the provider."""

    model_config = ConfigDict(from_attributes=True)

    provider: str
    authorization_url: str
    state_token: str


class SyncResponse(BaseModel):
    """Status of the last OAuth token sync for a provider connection."""

    model_config = ConfigDict(from_attributes=True)

    provider: str
    status: str
    last_synced_at: datetime | None = None
    error_message: str | None = None


__all__ = [
    "ApproveRecommendationRequest",
    "AttributionMatrixResponse",
    "BowtieSummaryResponse",
    "ChannelDetailResponse",
    "LucasRecommendationResponse",
    "OAuthConnectRequest",
    "OAuthConnectResponse",
    "RejectRecommendationRequest",
    "ReferralsResponse",
    "ReferrerEntryResponse",
    "StageDetailResponse",
    "SyncResponse",
]
