/**
 * PaymentStep — payment redirect step in the booking widget.
 *
 * Handles Stripe / MercadoPago iframe redirect:
 * - Displays amount + booking summary
 * - On "Pagar" click: calls onPaymentRedirect → BookingWidgetRoot posts
 *   widget:payment-redirect message to parent → parent opens checkout in new tab
 *
 * Per 03-arch-fe.md § 9 + spec § 5.4 (payment_processing state).
 * Spanish neutro LatAm. No voseo.
 */

import { cn } from "../lib/cn";

const COPY = {
  title: "Pago",
  summary: "Resumen de tu cita",
  amount: "Total a pagar",
  depositLabel: "Depósito requerido",
  cta: "Pagar ahora",
  back: "Atrás",
  processing: "Procesando...",
  redirectNote: "Serás redirigido al portal de pago seguro.",
  errorPrefix: "Error al iniciar el pago: ",
} as const;

export interface PaymentStepProps {
  /** Amount in decimal string (e.g. "150.00") */
  amount: string;
  /** Currency code (e.g. "USD", "ARS", "MXN") */
  currency: string;
  /** Offer name for display */
  offerName: string;
  /** ISO slot for display */
  slotIso: string;
  /** Whether this is a deposit-only payment */
  isDepositOnly: boolean;
  /** Checkout URL (pre-generated by BE at booking creation time) */
  checkoutUrl: string | null;
  onPaymentRedirect: (url: string) => void;
  onBack: () => void;
  isLoading: boolean;
  errorMessage?: string | null;
}

function formatSlotDisplay(isoString: string): string {
  try {
    const date = new Date(isoString);
    return date.toLocaleDateString("es-419", {
      weekday: "long",
      day: "numeric",
      month: "long",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return isoString;
  }
}

export function PaymentStep({
  amount,
  currency,
  offerName,
  slotIso,
  isDepositOnly,
  checkoutUrl,
  onPaymentRedirect,
  onBack,
  isLoading,
  errorMessage,
}: PaymentStepProps) {
  function handlePay() {
    if (!checkoutUrl || isLoading) return;
    onPaymentRedirect(checkoutUrl);
  }

  const canPay = Boolean(checkoutUrl) && !isLoading;

  return (
    <div className="flex flex-col h-full" role="region" aria-label="Paso de pago">
      {/* Header */}
      <div className="px-4 py-3 border-b border-gray-100">
        <h2 className="text-base font-semibold text-gray-900">{COPY.title}</h2>
      </div>

      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {/* Booking summary card */}
        <div className="rounded-lg border border-gray-100 bg-gray-50 px-4 py-3 space-y-2">
          <div className="text-xs font-medium text-gray-500 uppercase tracking-wide">
            {COPY.summary}
          </div>
          <div className="text-sm font-medium text-gray-900">{offerName}</div>
          <div className="text-xs text-gray-500">{formatSlotDisplay(slotIso)}</div>
        </div>

        {/* Amount display */}
        <div className="flex items-center justify-between px-4 py-3 rounded-lg bg-blue-50 border border-blue-100">
          <span className="text-sm text-blue-800 font-medium">
            {isDepositOnly ? COPY.depositLabel : COPY.amount}
          </span>
          <span className="text-lg font-bold text-blue-900">
            {currency} {amount}
          </span>
        </div>

        {/* Redirect note */}
        <p className="text-xs text-gray-400 text-center">{COPY.redirectNote}</p>

        {/* Error */}
        {errorMessage && (
          <div role="alert" className="rounded-lg bg-red-50 border border-red-200 px-4 py-3 text-sm text-red-700">
            {COPY.errorPrefix}{errorMessage}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="border-t border-gray-100 px-4 py-4 flex gap-3">
        <button
          type="button"
          onClick={onBack}
          disabled={isLoading}
          className={cn(
            "flex-1 px-4 py-2 text-sm font-medium text-gray-700",
            "border border-gray-300 rounded-lg",
            "hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-400",
            "disabled:opacity-40"
          )}
        >
          {COPY.back}
        </button>
        <button
          type="button"
          onClick={handlePay}
          disabled={!canPay}
          aria-disabled={!canPay}
          aria-busy={isLoading}
          className={cn(
            "flex-1 px-4 py-2 text-sm font-medium rounded-lg transition-colors",
            "focus:outline-none focus:ring-2 focus:ring-blue-500",
            canPay
              ? "bg-blue-600 hover:bg-blue-700 text-white"
              : "bg-gray-100 text-gray-400 cursor-not-allowed"
          )}
        >
          {isLoading ? COPY.processing : COPY.cta}
        </button>
      </div>
    </div>
  );
}
