# cap: crm.crm-consent-optout
# story-origin: TBD
"""MessageRepository — dual-scope async repository (T-inbox-be-2).

Inherits CompoundScopeRepositoryBase with scope_field="clinic_id" to enforce
the HIPAA-lite dual filter: tenant_id AND clinic_id on every query.

Custom methods:
- list_for_conversation(): paginated message list ordered by sent_at ASC
- soft_delete():           set deleted_at (NEVER hard DELETE)
- create():                persist new message row
- mark_retracted():        update retraction state on message row
- find_patient_reply_after(): find first patient reply after given message

PHI obligations (hipaa-lite.md § Regla cardinal):
1. tenant_id + clinic_id dual filter mandatory (via CompoundScopeRepositoryBase)
2. transcription_text is PHI — sanitize before logs (service layer enforces)
3. Soft delete only — no hard DELETE ever

downstream-regression-na: brand-local vitalia CRM infrastructure repo
"""

from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID

import structlog
from luana_core_platform.repositories.compound_scope_repository import (
    CompoundScopeRepositoryBase,
)
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from src.modules.vitalia.crm.infrastructure.persistence.models.message_model import (
    MessageModel,
)

logger = structlog.get_logger()


class MessageRepository(CompoundScopeRepositoryBase[MessageModel, UUID]):
    """Async repository for vitalia_messages.

    Dual-scope isolation: tenant_id + clinic_id (scope_field='clinic_id').
    Every query automatically filters both axes + excludes soft-deleted rows.
    """

    MODEL = MessageModel

    def __init__(self, *, session: AsyncSession) -> None:
        """Initialize with clinic_id as the secondary scope axis.

        Args:
            session: Async SQLAlchemy session (injected by DI).
        """
        super().__init__(session=session, scope_field="clinic_id")

    async def list_for_conversation(
        self,
        *,
        conversation_id: UUID,
        tenant_id: UUID,
        clinic_id: UUID,
        limit: int = 50,
        offset: int = 0,
    ) -> list[MessageModel]:
        """List messages for a conversation, ordered chronologically (sent_at ASC).

        PHI dual filter applied: tenant_id AND clinic_id mandatory.
        Soft-deleted messages excluded automatically.

        Args:
            conversation_id: UUID of the parent conversation.
            tenant_id:       Root tenant UUID.
            clinic_id:       Clinic UUID (HIPAA-lite second scope filter).
            limit:           Page size. Default 50.
            offset:          Page offset. Default 0.

        Returns:
            List of MessageModel instances ordered by sent_at ASC.
        """
        scope_attr = self._scope_attr()
        stmt = (
            select(MessageModel)
            .where(MessageModel.conversation_id == conversation_id)
            .where(MessageModel.tenant_id == tenant_id)
            .where(scope_attr == clinic_id)
            .where(MessageModel.deleted_at.is_(None))
            .order_by(MessageModel.sent_at.asc())
            .offset(offset)
            .limit(limit)
        )
        result = await self._session.execute(stmt)
        rows = list(result.scalars().all())
        logger.debug(
            "message_repo.list_for_conversation",
            conversation_id=str(conversation_id),
            tenant_id=str(tenant_id),
            clinic_id=str(clinic_id),
            count=len(rows),
        )
        return rows

    async def create(
        self,
        *,
        id: UUID,
        tenant_id: UUID,
        clinic_id: UUID,
        conversation_id: UUID,
        channel: str,
        external_message_id: str | None,
        sender_type: str,
        sender_user_id: UUID | None,
        body_text: str | None,
        media_kind: str | None,
        media_url: str | None,
        media_duration_s: int | None,
        media_phi_flagged: bool,
        transcription_text: str | None,
        transcription_confidence: float | None,
        retracted_at: datetime | None,
        retracted_by_user_id: UUID | None,
        retracted_reason: str | None,
        retract_succeeded: bool | None,
        handler_mode: str,
        cache_hit_rate: float | None,
        llm_cost_usd: float | None,
        sent_at: datetime,
        delivered_at: datetime | None,
        read_at: datetime | None,
    ) -> MessageModel:
        """Persist a new message row.

        PHI dual filter: tenant_id AND clinic_id mandatory on all writes.

        Args:
            id: Message UUID (pre-generated by service layer).
            tenant_id: Root tenant UUID.
            clinic_id: Clinic UUID (HIPAA-lite second scope filter).
            conversation_id: Parent conversation UUID.
            channel: Channel name (e.g. 'whatsapp', 'instagram').
            external_message_id: Optional WA/IG message id.
            sender_type: 'patient' | 'agent_ai' | 'agent_human' | 'system'.
            sender_user_id: User UUID (None for AI/system messages).
            body_text: Message text (PHI — sanitize before traces).
            media_kind: 'audio' | 'image' | 'video' | 'document' | None.
            media_url: Media URL (PHI reference).
            media_duration_s: Audio duration in seconds.
            media_phi_flagged: Whether media contains PHI.
            transcription_text: Whisper STT result (PHI).
            transcription_confidence: Whisper confidence score.
            retracted_at: Retraction timestamp (None for active).
            retracted_by_user_id: User who retracted (None for active).
            retracted_reason: Retract reason string.
            retract_succeeded: Whether channel retract API succeeded.
            handler_mode: Context snapshot at send time ('ai' | 'human').
            cache_hit_rate: LLM cache hit rate (None for human messages).
            llm_cost_usd: LLM cost in dollars (None for human messages).
            sent_at: When message was sent.
            delivered_at: When message was delivered (None initially).
            read_at: When message was read (None initially).

        Returns:
            Created MessageModel instance.
        """
        now = datetime.now(tz=timezone.utc)
        row = MessageModel(
            id=id,
            tenant_id=tenant_id,
            clinic_id=clinic_id,
            conversation_id=conversation_id,
            channel=channel,
            external_message_id=external_message_id,
            sender_type=sender_type,
            sender_user_id=sender_user_id,
            body_text=body_text,
            media_kind=media_kind,
            media_url=media_url,
            media_duration_s=media_duration_s,
            media_phi_flagged=media_phi_flagged,
            transcription_text=transcription_text,
            transcription_confidence=transcription_confidence,
            retracted_at=retracted_at,
            retracted_by_user_id=retracted_by_user_id,
            retracted_reason=retracted_reason,
            retract_succeeded=retract_succeeded,
            handler_mode=handler_mode,
            cache_hit_rate=cache_hit_rate,
            llm_cost_usd=llm_cost_usd,
            sent_at=sent_at,
            delivered_at=delivered_at,
            read_at=read_at,
            created_at=now,
            updated_at=now,
        )
        self._session.add(row)
        await self._session.flush()
        logger.info(
            "message_repo.create",
            message_id=str(row.id),
            tenant_id=str(tenant_id),
            clinic_id=str(clinic_id),
            conversation_id=str(conversation_id),
            sender_type=sender_type,
        )
        return row

    async def mark_retracted(
        self,
        *,
        message_id: UUID,
        tenant_id: UUID,
        clinic_id: UUID,
        retracted_by_user_id: UUID,
        retracted_at: datetime,
        retract_succeeded: bool,
        retracted_reason: str,
    ) -> bool:
        """Update retraction state on a message row.

        PHI dual filter applied: only updates row with matching
        tenant_id AND clinic_id. Never issues a hard DELETE.

        Args:
            message_id: UUID of the message to mark retracted.
            tenant_id: Root tenant UUID.
            clinic_id: Clinic UUID (HIPAA-lite second scope filter).
            retracted_by_user_id: User who performed the retraction.
            retracted_at: Retraction timestamp.
            retract_succeeded: Whether channel retract API succeeded.
            retracted_reason: Reason string (e.g. 'user_undo').

        Returns:
            True if the row was updated (rowcount == 1).
            False if not found or wrong tenant/clinic scope.
        """
        scope_attr = self._scope_attr()
        now = datetime.now(tz=timezone.utc)
        stmt = (
            update(MessageModel)
            .where(MessageModel.id == message_id)
            .where(MessageModel.tenant_id == tenant_id)
            .where(scope_attr == clinic_id)
            .where(MessageModel.retracted_at.is_(None))  # idempotency guard
            .values(
                retracted_at=retracted_at,
                retracted_by_user_id=retracted_by_user_id,
                retracted_reason=retracted_reason,
                retract_succeeded=retract_succeeded,
                updated_at=now,
            )
        )
        result = await self._session.execute(stmt)
        success = result.rowcount == 1  # type: ignore[union-attr]
        logger.info(
            "message_repo.mark_retracted",
            message_id=str(message_id),
            tenant_id=str(tenant_id),
            clinic_id=str(clinic_id),
            retract_succeeded=retract_succeeded,
            success=success,
        )
        return success

    async def find_patient_reply_after(
        self,
        *,
        message_id: UUID,
        conversation_id: UUID,
        tenant_id: UUID,
        clinic_id: UUID,
    ) -> MessageModel | None:
        """Find the first patient reply after a given message in a conversation.

        Used by RetractMessageService to check for OCC conflict (SC-03):
        if patient replied after the AI message, retraction is blocked (→ 409).

        PHI dual filter applied: tenant_id AND clinic_id mandatory.

        Args:
            message_id: UUID of the AI message whose sent_at is the lower bound.
            conversation_id: Conversation scope UUID.
            tenant_id: Root tenant UUID.
            clinic_id: Clinic UUID (HIPAA-lite second scope filter).

        Returns:
            First patient MessageModel after the given message, or None.
        """
        scope_attr = self._scope_attr()
        # Subquery: get sent_at of the anchor message
        anchor_stmt = (
            select(MessageModel.sent_at)
            .where(MessageModel.id == message_id)
            .where(MessageModel.tenant_id == tenant_id)
            .where(scope_attr == clinic_id)
            .scalar_subquery()
        )
        stmt = (
            select(MessageModel)
            .where(MessageModel.conversation_id == conversation_id)
            .where(MessageModel.tenant_id == tenant_id)
            .where(scope_attr == clinic_id)
            .where(MessageModel.sender_type == "patient")
            .where(MessageModel.deleted_at.is_(None))
            .where(MessageModel.sent_at > anchor_stmt)
            .order_by(MessageModel.sent_at.asc())
            .limit(1)
        )
        result = await self._session.execute(stmt)
        row = result.scalar_one_or_none()
        logger.debug(
            "message_repo.find_patient_reply_after",
            message_id=str(message_id),
            conversation_id=str(conversation_id),
            tenant_id=str(tenant_id),
            clinic_id=str(clinic_id),
            found=row is not None,
        )
        return row

    async def soft_delete(
        self,
        *,
        message_id: UUID,
        tenant_id: UUID,
        clinic_id: UUID,
    ) -> bool:
        """Soft-delete a message by setting deleted_at = now().

        PHI dual filter applied: only deletes row with matching
        tenant_id AND clinic_id. Never issues a hard DELETE.

        Args:
            message_id: UUID of the message to soft-delete.
            tenant_id:  Root tenant UUID.
            clinic_id:  Clinic UUID (HIPAA-lite second scope filter).

        Returns:
            True if the row was updated (rowcount == 1).
            False if not found or wrong tenant/clinic scope.
        """
        scope_attr = self._scope_attr()
        now = datetime.now(tz=timezone.utc)
        stmt = (
            update(MessageModel)
            .where(MessageModel.id == message_id)
            .where(MessageModel.tenant_id == tenant_id)
            .where(scope_attr == clinic_id)
            .where(MessageModel.deleted_at.is_(None))
            .values(deleted_at=now, updated_at=now)
        )
        result = await self._session.execute(stmt)
        success = result.rowcount == 1  # type: ignore[union-attr]
        logger.info(
            "message_repo.soft_delete",
            message_id=str(message_id),
            tenant_id=str(tenant_id),
            clinic_id=str(clinic_id),
            success=success,
        )
        return success
