# cap: platform.product-map-zonas
"""generate_actions_index.py — Thin compositor: capabilites → actions-index.json (Plano 2).

Story: vitalia-paradigm-map-zones · T-1 (F4)
ADR: vitalia/docs/architecture/ADR-vitalia-005-capability-model-4-dimensions.md

NO-NEW-LAYER decision: reuses _code-index.json (cap↔files already generated by
generate_code_to_cap_index.py) and composes with dev_preview from cap YAMLs.

Lee:
  - {brand}/docs/product/capabilities/_code-index.json   (ya existente — cap↔files)
  - {brand}/docs/product/capabilities/**/*.yaml            (dev_preview: api_endpoints, route, main_component, e2e_test)

Produce (gitignored R3):
  - {brand}/docs/product/capabilities/_actions-index.json
    Shape: {
      "generated_at": "ISO8601",
      "brand": "vitalia",
      "actions": {
        "<cap_id>": {
          "cap_id": str,
          "map_box": str | null,
          "route": str | null,
          "api_endpoints": list[str],
          "main_component": str | null,
          "e2e_test": str | null,
          "files": list[str],     # from _code-index.json cap_to_files
          "user_visible": bool
        }
      },
      "summary": {...}
    }

Uso:
    python3 scripts/generate_actions_index.py --brand vitalia [--out PATH] [--verbose]
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def load_code_index(caps_dir: Path) -> dict[str, Any]:
    """Load existing _code-index.json (cap → files). Returns empty if missing."""
    idx_path = caps_dir / "_code-index.json"
    if not idx_path.exists():
        return {"cap_to_files": {}, "code_to_cap": {}}
    try:
        return json.loads(idx_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"cap_to_files": {}, "code_to_cap": {}}


def parse_cap_frontmatter(cap_path: Path) -> dict[str, Any]:
    """Parse only YAML frontmatter from a cap YAML file."""
    try:
        content = cap_path.read_text(encoding="utf-8")
    except OSError:
        return {}

    if content.startswith("---\n"):
        parts = content.split("\n---\n", 2)
        yaml_text = parts[0][4:] if len(parts) >= 2 else content[4:]
    elif "\n---\n" in content:
        yaml_text = content.split("\n---\n", 1)[0]
    else:
        yaml_text = content

    try:
        data = yaml.safe_load(yaml_text)
        return data if isinstance(data, dict) else {}
    except yaml.YAMLError:
        return {}


def collect_caps(caps_dir: Path) -> dict[str, dict[str, Any]]:
    """Collect all cap YAMLs and extract relevant fields."""
    caps: dict[str, dict[str, Any]] = {}

    for module_dir in sorted(caps_dir.iterdir()):
        if not module_dir.is_dir() or module_dir.name.startswith("_"):
            continue
        for yaml_file in sorted(module_dir.glob("*.yaml")):
            if yaml_file.name.startswith("_"):
                continue
            data = parse_cap_frontmatter(yaml_file)
            if not data:
                continue

            cap_id = data.get("capability_id") or data.get("slug")
            if not cap_id:
                # Derive from path
                cap_id = f"vitalia.{module_dir.name}.{yaml_file.stem}"

            dev_preview = data.get("dev_preview") or {}

            caps[cap_id] = {
                "cap_id": cap_id,
                "slug": data.get("slug", yaml_file.stem),
                "module": module_dir.name,
                "map_box": data.get("map_box"),
                "user_visible": data.get("user_visible", True),
                "route": dev_preview.get("route"),
                "api_endpoints": dev_preview.get("api_endpoints") or [],
                "main_component": dev_preview.get("main_component"),
                "e2e_test": dev_preview.get("e2e_test"),
                "files": [],  # will be filled from code_index
            }

    return caps


def merge_with_code_index(
    caps: dict[str, dict[str, Any]],
    code_index: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    """Merge cap data with code index (cap_to_files)."""
    cap_to_files = code_index.get("cap_to_files", {})

    for cap_id, cap_data in caps.items():
        # Try exact match first, then slug-based match
        files = cap_to_files.get(cap_id, [])

        if not files:
            # Try matching by module.slug pattern
            slug = cap_data.get("slug", "")
            module = cap_data.get("module", "")
            alt_key = f"{module}.{slug}"
            files = cap_to_files.get(alt_key, [])

        cap_data["files"] = files

    return caps


def generate_actions_index(
    brand: str,
    brand_dir: Path,
    out_path: Path | None = None,
    verbose: bool = False,
) -> dict[str, Any]:
    """Generate the actions index. Returns the index dict."""
    caps_dir = brand_dir / "docs" / "product" / "capabilities"
    if not caps_dir.exists():
        print(f"ERROR: caps dir no existe: {caps_dir}", file=sys.stderr)
        sys.exit(1)

    # Load existing code index (EXTEND, not recreate)
    code_index = load_code_index(caps_dir)
    if verbose:
        cap_to_files_count = len(code_index.get("cap_to_files", {}))
        print(f"  _code-index.json loaded: {cap_to_files_count} cap-to-files entries")

    # Collect caps from YAML files
    caps = collect_caps(caps_dir)
    if verbose:
        print(f"  Cap YAMLs collected: {len(caps)}")

    # Merge with code index
    caps = merge_with_code_index(caps, code_index)

    # Build summary
    total_caps = len(caps)
    caps_with_route = sum(1 for c in caps.values() if c.get("route"))
    caps_with_api = sum(1 for c in caps.values() if c.get("api_endpoints"))
    caps_with_files = sum(1 for c in caps.values() if c.get("files"))
    user_visible_caps = sum(1 for c in caps.values() if c.get("user_visible"))

    index: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "brand": brand,
        "actions": caps,
        "summary": {
            "total_caps": total_caps,
            "caps_with_route": caps_with_route,
            "caps_with_api_endpoints": caps_with_api,
            "caps_with_code_files": caps_with_files,
            "user_visible_caps": user_visible_caps,
            "infra_caps": total_caps - user_visible_caps,
        },
    }

    # Write output
    if out_path is None:
        out_path = caps_dir / "_actions-index.json"

    out_path.write_text(json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8")

    if verbose:
        print(f"  Written: {out_path}")
        print(
            f"  Total caps: {total_caps} · with_route: {caps_with_route} · with_api: {caps_with_api} · user_visible: {user_visible_caps}"
        )

    return index


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--brand", default="vitalia", help="Brand slug (default: vitalia)")
    parser.add_argument("--out", help="Output path (default: {brand}/docs/product/capabilities/_actions-index.json)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    brand_dir = REPO_ROOT / args.brand
    if not brand_dir.exists():
        print(f"ERROR: brand dir no existe: {brand_dir}", file=sys.stderr)
        return 1

    out_path = Path(args.out) if args.out else None
    print(f"=== generate_actions_index · brand={args.brand} ===")

    generate_actions_index(
        brand=args.brand,
        brand_dir=brand_dir,
        out_path=out_path,
        verbose=args.verbose or True,
    )

    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
