#!/usr/bin/env python3
"""
scan_promotables.py — Auto-detect patrones promotable brand→core.

Lee:
- {brand}/docs/learnings/*.md (filter promotable: candidate | yes en frontmatter)

Heurísticas (basic, ampliable):
1. Group by `target_core_package` declarado en learning
2. Si ≥2 brands declaran mismo target → cluster candidato
3. Si learning tiene `applies_to_other_brands_potentially: [...]` con ≥1 brand → flag

Output:
- docs/promotion-protocol/scan-{date}.yaml — listado clusters + razón

Uso:
    python3 scripts/scan_promotables.py            # full scan + write
    python3 scripts/scan_promotables.py --dry-run  # solo print, no write
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
PROMOTION_DIR = REPO_ROOT / "docs" / "promotion-protocol"

# Active brands (have docs/learnings/) — read from the harness seam project.config.yaml
# (W5b 2026-06-09 · brands.active). No hardcoded enum: a new product/brand is picked up
# from the seam, never by editing this script (charter §3 DIP · pending-bootstrap brands
# live under brands.pending_bootstrap until they have a docs surface).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from harness_config import get as _cfg  # noqa: E402 — own script dir put on sys.path above

BRAND_SLUGS = _cfg("brands.active", pluck="slug")


def parse_frontmatter(content: str) -> dict[str, Any]:
    """Extract YAML frontmatter from markdown."""
    match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return {}
    fm: dict[str, Any] = {}
    for line in match.group(1).splitlines():
        line_stripped = line.strip()
        if not line_stripped or line_stripped.startswith("#"):
            continue
        if ":" not in line_stripped:
            continue
        key, _, value = line_stripped.partition(":")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # Handle list values (basic)
        if value.startswith("[") and value.endswith("]"):
            value = [v.strip().strip("'\"") for v in value[1:-1].split(",") if v.strip()]
        fm[key] = value
    return fm


def scan_brand_learnings(slug: str) -> list[dict[str, Any]]:
    """Walk {brand}/docs/learnings/*.md and return entries with promotable=candidate|yes."""
    learnings_dir = REPO_ROOT / slug / "docs" / "learnings"
    if not learnings_dir.exists():
        return []
    promotable_entries: list[dict[str, Any]] = []
    for md_file in learnings_dir.glob("*.md"):
        if md_file.name == "README.md":
            continue
        fm = parse_frontmatter(md_file.read_text(encoding="utf-8"))
        promotable = fm.get("promotable", "no")
        if promotable in ("candidate", "yes"):
            promotable_entries.append(
                {
                    "brand": slug,
                    "file": str(md_file.relative_to(REPO_ROOT)),
                    "slug": fm.get("slug", md_file.stem),
                    "promotable": promotable,
                    "target_core_package": fm.get("target_core_package", "unspecified"),
                    "applies_to_other_brands_potentially": fm.get(
                        "applies_to_other_brands_potentially", []
                    ),
                    "date": fm.get("date", "unknown"),
                }
            )
    return promotable_entries


def cluster_candidates(all_entries: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    """Group entries by target_core_package. Cluster only if ≥2 brands."""
    by_target: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in all_entries:
        target = entry["target_core_package"]
        if target == "unspecified":
            continue
        by_target[target].append(entry)

    clusters: dict[str, list[dict[str, Any]]] = {}
    for target, entries in by_target.items():
        brands = {e["brand"] for e in entries}
        if len(brands) >= 2:
            clusters[target] = entries
    return clusters


def render_yaml(today: str, all_entries: list[dict[str, Any]], clusters: dict) -> str:
    """Render simple YAML output (no PyYAML dep, hand-roll basic)."""
    lines = [
        f"# Auto-gen scan-{today}.yaml — promotable patterns scan",
        f"# Generated by scripts/scan_promotables.py",
        f"",
        f"scan_date: {today}",
        f"total_entries_scanned: {len(all_entries)}",
        f"total_promotable_candidates: {len([e for e in all_entries if e['promotable'] in ('candidate', 'yes')])}",
        f"clusters_found: {len(clusters)}",
        f"",
        f"---",
        f"",
        f"# All promotable entries (per brand)",
        f"promotable_entries:",
    ]
    if not all_entries:
        lines.append("  []  # no entries found — pobla {brand}/docs/learnings/ con promotable: candidate|yes")
    for entry in all_entries:
        lines.append(f"  - brand: {entry['brand']}")
        lines.append(f"    slug: {entry['slug']}")
        lines.append(f"    file: {entry['file']}")
        lines.append(f"    promotable: {entry['promotable']}")
        lines.append(f"    target_core_package: {entry['target_core_package']}")
        lines.append(f"    date: {entry['date']}")
        applies = entry["applies_to_other_brands_potentially"]
        if isinstance(applies, list) and applies:
            lines.append(f"    applies_to_other_brands_potentially: {applies}")
        else:
            lines.append(f"    applies_to_other_brands_potentially: []")
        lines.append("")

    lines += [
        "---",
        "",
        "# Clusters detected (≥2 brands declaran mismo target_core_package)",
        "clusters:",
    ]
    if not clusters:
        lines.append("  {}  # no clusters yet — necesita ≥2 brands con mismo target_core_package")
    for target, entries in clusters.items():
        brands = sorted({e["brand"] for e in entries})
        lines.append(f"  {target}:")
        lines.append(f"    brands: {brands}")
        lines.append(f"    entries_count: {len(entries)}")
        lines.append(f"    recommended_action: open promotion proposal in docs/promotion-protocol/proposals/")
        lines.append("")

    lines += [
        "---",
        "",
        "# Next actions",
        "next_actions:",
    ]
    if not clusters:
        lines.append("  - Acumula learnings con promotable: candidate|yes en {brand}/docs/learnings/")
        lines.append("  - Cuando ≥2 brands declaren mismo target_core_package, este script flagea cluster")
    else:
        for target, entries in clusters.items():
            brands = sorted({e["brand"] for e in entries})
            lines.append(
                f"  - Open proposal {target} (brands: {', '.join(brands)}) — "
                f"copy template-proposal.md, fill origin_learnings"
            )
    return "\n".join(lines) + "\n"


def main(dry_run: bool = False) -> int:
    today = date.today().isoformat()
    all_entries: list[dict[str, Any]] = []
    for slug in BRAND_SLUGS:
        all_entries.extend(scan_brand_learnings(slug))

    clusters = cluster_candidates(all_entries)
    output = render_yaml(today, all_entries, clusters)

    if dry_run:
        print(output)
        return 0

    PROMOTION_DIR.mkdir(parents=True, exist_ok=True)
    output_path = PROMOTION_DIR / f"scan-{today}.yaml"
    output_path.write_text(output, encoding="utf-8")
    print(f"scan_promotables: wrote {output_path.relative_to(REPO_ROOT)}")
    print(f"  total entries scanned: {len(all_entries)}")
    print(f"  clusters detected: {len(clusters)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(dry_run="--dry-run" in sys.argv))
