# cap: brand_studio.brand-studio-medical-sections
# story-origin: vitalia-fase2-s7-TBD
"""VoicePreview domain value object — compiled BRAND_VOICE slot 5 sample.

Deterministic, no LLM dispatch. Generated by VoicePreviewService consuming
PersonalityCompiler.compile() from core engine.

Anti-creep: NEVER store user-typed voice content verbatim. Only compiled output.
downstream-regression-na: brand-local VO vitalia
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime


@dataclass(frozen=True)
class VoicePreview:
    """Compiled BRAND_VOICE slot 5 sample (deterministic, no LLM dispatch).

    Generated by VoicePreviewService consuming PersonalityCompiler from
    core/luana-core-brand-studio. Output is a textual sample shown in UI
    footer of sub-sub-tab Voz.
    """

    personality_profile_id: str  # opaque hash hex (for cache key)
    sample_whatsapp: str  # canal WhatsApp short greeting
    sample_email_reactivation: str  # canal email longer reactivation
    compiled_at: datetime
    compiler_version: str  # v2 cementado sales-agent
    cache_hit: bool = False
