# cap: marketing.lucas-stage-recommendations
# story-origin: TBD
"""LucasRecommendation domain entity — pure Python, no framework imports.

Business invariants:
- Only OPEN recommendations can be approved or rejected.
- approve() sets undo_until = approved_at + 5 minutes.
- undo() reverts to OPEN only within the undo_until window.
- expire() only affects OPEN recommendations.
- Expired recommendations (expires_at in past) cannot be approved.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

from src.modules.vitalia.marketing.domain.enums import (
    BowtieStage,
    RecommendationStatus,
    RejectReason,
)
from src.modules.vitalia.marketing.domain.exceptions import (
    ExpiredRecommendationError,
    InvalidStateTransitionError,
    UndoWindowExpiredError,
)

_UNDO_WINDOW_MINUTES = 5


@dataclass
class LucasRecommendation:
    """A marketing recommendation generated by Lucas AI for a clinic.

    Represents a single actionable suggestion (e.g., increase ad budget,
    adjust campaign targeting) in the bowtie marketing funnel.
    """

    id: uuid.UUID
    tenant_id: uuid.UUID
    clinic_id: uuid.UUID
    stage: BowtieStage
    recommendation_kind: str
    title: str
    body: str
    rationale_json: dict[str, Any]
    priority: int
    status: RecommendationStatus
    expires_at: datetime
    created_at: datetime
    updated_at: datetime

    # Optional fields
    action_payload_json: dict[str, Any] | None = None
    confidence_pct: int | None = None
    projected_impact_text: str | None = None
    approved_by_user_id: uuid.UUID | None = None
    approved_at: datetime | None = None
    undo_until: datetime | None = None
    rejected_by_user_id: uuid.UUID | None = None
    rejected_at: datetime | None = None
    reject_reason: RejectReason | None = None
    deleted_at: datetime | None = None

    def approve(self, *, user_id: uuid.UUID) -> None:
        """Approve this recommendation.

        Transitions status OPEN → APPROVED, sets undo_until to 5 minutes
        from now, and records the approving user.

        Raises:
            ExpiredRecommendationError: if expires_at is in the past.
            InvalidStateTransitionError: if status is not OPEN.
        """
        now = datetime.now(UTC)

        if now > self.expires_at:
            raise ExpiredRecommendationError()

        if self.status != RecommendationStatus.OPEN:
            raise InvalidStateTransitionError(
                current_status=self.status.value,
                attempted_action="approve",
            )

        self.status = RecommendationStatus.APPROVED
        self.approved_by_user_id = user_id
        self.approved_at = now
        self.undo_until = now + timedelta(minutes=_UNDO_WINDOW_MINUTES)
        self.updated_at = now

    def reject(self, *, user_id: uuid.UUID, reason: RejectReason) -> None:
        """Reject this recommendation.

        Transitions status OPEN → REJECTED and records reason + user.

        Raises:
            InvalidStateTransitionError: if status is not OPEN.
        """
        if self.status != RecommendationStatus.OPEN:
            raise InvalidStateTransitionError(
                current_status=self.status.value,
                attempted_action="reject",
            )

        now = datetime.now(UTC)
        self.status = RecommendationStatus.REJECTED
        self.rejected_by_user_id = user_id
        self.rejected_at = now
        self.reject_reason = reason
        self.updated_at = now

    def undo(self) -> None:
        """Undo a recent approval — reverts APPROVED → OPEN.

        Only valid within the 5-minute undo window set by approve().

        Raises:
            UndoWindowExpiredError: if undo_until has passed.
            InvalidStateTransitionError: if status is not APPROVED.
        """
        if self.status != RecommendationStatus.APPROVED:
            raise InvalidStateTransitionError(
                current_status=self.status.value,
                attempted_action="undo",
            )

        now = datetime.now(UTC)
        if self.undo_until is None or now > self.undo_until:
            raise UndoWindowExpiredError()

        self.status = RecommendationStatus.OPEN
        self.approved_at = None
        self.approved_by_user_id = None
        self.undo_until = None
        self.updated_at = now

    def expire(self) -> None:
        """Mark this recommendation as expired (cron job action).

        Only affects OPEN recommendations — approved/rejected/expired
        recommendations are not changed.
        """
        if self.status == RecommendationStatus.OPEN:
            now = datetime.now(UTC)
            self.status = RecommendationStatus.EXPIRED
            self.updated_at = now
